version: '1'

services:
  app:
    image: 'irbis:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/irbis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: 'postgres:15.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=irbis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres