client-api-token: encrypted-data
statistics-folder: stats

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Adiqq228}
  flyway:
    schemas: ${DB_SCHEMA:irbis}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none